name: Wiki Deploy

on:
  push:
    branches:
      - test
      - prod

jobs:
  build:
    name: Build wiki book
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install mdbook
      uses: MineBartekSA/quick-mdbook@v1.1
    - name: Build book
      env:
        SCRIPT: https://gist.githubusercontent.com/MineBartekSA/5234f09c1048f9ba007d0a26a8fd654e/raw/github-release.sh
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        curl -fsSL $SCRIPT | bash -s -- NilPointer-Software/mdbook-discord-components
        tar xzf mdbook-discord-components-*.tar.gz
        mdbook build
    - name: Upload book
      uses: actions/upload-artifact@v3
      with:
        name: book
        path: book

  deploy-prod:
    name: Deploy production wiki
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Prepare to fetch book
      run: |
        mv test ..
        rm -rf *
    - name: Fetch book artifact
      uses: actions/download-artifact@v3
      with:
        name: book
    - name: Deploy
      run: |
        mv ../test .
        git config user.name "Github Actions"
        git config user.email ""
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages

  deploy-test:
    name: Deploy test wiki
    needs: build
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Prepare to fetch book
      run: |
        rm -rf test/*
    - name: Fetch book artifact
      uses: actions/download-artifact@v3
      with:
        name: book
        path: test
    - name: Deploy
      run: |
        git config user.name "Github Actions"
        git config user.email ""
        git add .
        git commit -m "Deploy test $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
